<a href="https://colab.research.google.com/github/rainieluo2016/Self-Learning-Note/blob/learn%2Fcnn/backward_propagraion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Study Material

+ [optimization2](https://cs231n.github.io/optimization-2/)
+ [section 2.1 of CNN and LSTM for multimodal wearable activity recognition](https://www.semanticscholar.org/paper/Deep-Convolutional-and-LSTM-Recurrent-Neural-for-Ordonez-Roggen/c8599a64beec9ec141a97c8117aa5b1726c13223)
+ chpt 15 of hands on machine learning
+ chpt 6.5 deep learning

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Sigmoid Example


$f(w,x) = \frac{1}{1+e^{-(w_0x_0 + w_1x_1 + w_2)}}$

+ step 1 consider the layer as a whole $X = (w_0x_0 + w_1x_1 + w_2)$
  + then the sigmoid becomes $\sigma(x) = \frac{1}{1 + e^(-x)}$
+ step 2 find derivative of the $\sigma$
  + $\sigma(x) = \frac{1}{1+e^{-x}} \\\\
\rightarrow \hspace{0.3in} \frac{d\sigma(x)}{dx} = \frac{e^{-x}}{(1+e^{-x})^2} = \left( \frac{1 + e^{-x} - 1}{1 + e^{-x}} \right) \left( \frac{1}{1+e^{-x}} \right)
= \left( 1 - \sigma(x) \right) \sigma(x)$
+ step 3 feed back to each individual $x_i, w_i$
  + $dx_i = \frac{df}{dσ} * \frac{dσ}{dx} = ( 1 - \sigma(x) ) \sigma(x) * w_i$


In [ ]:
import math
import numpy as np
# define some random weights and data
w = np.array([2, -3, -3])
x = np.array([-1, -2])
# extend x with one extra identity at last for bias
x_bias = np.append(x, 1)

# forward pass
dot = w[0]*x[0] + w[1]*x[1] + w[2]
f = 1.0 / (1 + math.exp(-dot)) # sigmoid function

# chain rules to find the derivative for each variable
ddot = (1 - f) * f
dx = ddot * w[:-1]
dw = ddot * x_bias

print(f"derivative for x: {dx}")
print(f"derivative for w: {dw}")

derivative for x: [ 0.39322387 -0.5898358 ]
derivative for w: [-0.19661193 -0.39322387  0.19661193]


# Forward + bP

In [ ]:
# forward
W = np.random.randn(5, 10)
X = np.random.randn(10, 3)
D = W.dot(X)

print(f"W has shape {W.shape} , with value: {W}")
print(f"X has shape {X.shape} , with value: {X}")
print(f"D has shape {D.shape} , with value: {D}")

W has shape (5, 10) , with value: [[-0.40261417  1.64299611  0.381094    0.93842473  0.44456378 -0.48076815
   0.08215532  0.01030334  0.93029275 -1.76757218]
 [ 0.04928237 -0.64702943  1.10975445  0.57293608  0.57009131 -0.30159117
   0.19497826  1.13731066 -1.28421875  1.12721536]
 [-0.89746918 -1.57895452 -1.72175148 -0.03740742 -1.37983624 -0.61248215
  -0.09608762 -0.57250666  0.86285398 -0.33568827]
 [ 1.17896459  0.73239755 -1.27101736 -1.59607042 -0.79281732  0.10280488
  -0.35514108  0.79297707  1.30474519  0.16726522]
 [ 0.72840595  0.75972052 -0.51214684 -0.35827142 -0.18820696  0.59944314
  -1.59211985  0.18955882 -1.01575061  0.1796181 ]]
X has shape (10, 3) , with value: [[-1.0676337  -0.70312747  0.24862407]
 [-1.11224896  0.90799062  0.60128901]
 [ 0.67702787  0.384872   -0.17826734]
 [ 1.21713906 -1.17818274  0.42378994]
 [ 1.24497997  1.57256105  1.42780942]
 [-0.45570334  0.15314691  1.96959202]
 [ 0.03578309  0.07664374  0.19201267]
 [-0.42371331 -0.26231186  0.5348

In [ ]:
# now suppose we had the gradient on D from above in the circuit
dD = np.random.randn(*D.shape) # same shape as D
dD.shape

(5, 3)

In [ ]:
dW = dD.dot(X.T) #.T gives the transpose of the matrix
dX = W.T.dot(dD)

[RNN](https://web.stanford.edu/class/cs224n/index.html#schedule)

In [ ]:
x_bias

[-1, -2, 1]